version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      DB_HOST: ${HOST}
      DB_PORT: ${PORT}
      DB_USER: ${USER}
      DB_PASSWORD: ${PASSWORD}
      DB_NAME: ${DATABASE}
